### ISSUE TITLE
Contribute dynamic licensing to Chirpy theme

### ISSUE THREAD

**Issue by goodnightdaniel** [goodnightdaniel/goodnightdaniel.github.io#23]
- Add in theme config language support (`en: default: template: [here]` etc.)
- ask if this is something the theme wants as a feature for everyone
- clean it up
- contribute it

**Comment by goodnightdaniel** [comment]
```
en:
  default:
    template: "All Rights Reserved. See :LICENSE_NAME for details."
    name: "Licensing"
    link: "/licensing/"
  cc:
    template: "This post is licensed under :LICENSE_NAME by the author."
    name: "CC BY-NC-SA 4.0"
    link: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
es:
  default:
    template: "Todos los derechos reservados. Consulte :LICENSE_NAME para más detalles."
    name: "Licencia"
    link: "/licensing/"
  cc:
    template: "Este post está licenciado bajo :LICENSE_NAME por el autor."
    name: "CC BY-NC-SA 4.0"
    link: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
```
